<?xml version= "1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="camera">
  
  <xacro:include filename="$(find camera)/description/materials.xacro"/>
  <xacro:include filename="$(find camera)/description/shapes.xacro"/>
  
  <xacro:property name="camera_length" value="0.05" />
  <xacro:property name="camera_width" value="0.2" />
  <xacro:property name="camera_height" value="0.1" />
  
  <link name="base_link">
    <xacro:box mass="1" x="${camera_length}" y="${camera_width}" z="${camera_height}" color="blue">
      <origin xyz="0 0 ${camera_height/2}" rpy="0 0 0"/>
    </xacro:box>
  </link>
  
  <link name="camera_lens">
    <xacro:cylinder_visual radius="${camera_height/2 - 0.01}" height="${0.02}" color="red">
      <origin xyz="0.01 0 0" rpy="${pi/2} 0 ${pi/2} "/>
    </xacro:cylinder_visual>
  </link>
  
  <joint name="camera_optical_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_lens"/>
    <origin xyz="${camera_length/2} 0 ${camera_height/2}" rpy="0 0 0" />
  </joint>
  
  <gazebo reference="camera_lens">
      <sensor name="camera" type="camera">
        <always_on>1</always_on>
        <topic>camera</topic>
        <visualize>true</visualize>
        <update_rate>10</update_rate>
        <camera>
          <horizontal_fov>1.1</horizontal_fov>
          <image>
            <format>R8G8B8</format>
            <width>640</width>
            <height>480</height>
          </image>
          <clip>
            <near>0.05</near>
            <far>10.0</far>
          </clip>
        </camera>
      </sensor>
  </gazebo>
  
</robot>
      
